version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/Dechat/stellar-contracts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dechat/dex_with_fiat_frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
